import { StyleSheet } from "react-native";
import { colors } from "../../../theme/tokens";

export const styles = StyleSheet.create({
  row: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 12,
    borderBottomWidth: 4,
    paddingBottom: 12,
  },
  marker: {
    width: 14,
    height: 14,
    backgroundColor: colors.deepTeal,
    borderWidth: 2,
    borderColor: colors.ink,
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    borderBottomLeftRadius: 7,
    borderBottomRightRadius: 2,
    transform: [{ rotate: "-45deg" }],
  },
  input: {
    flex: 1,
    fontFamily: "Karla_400Regular",
    fontSize: 24,
    color: colors.ink,
    padding: 0,
  },
  helper: {
    fontFamily: "Karla_400Regular",
    fontSize: 14,
    color: colors.ink45,
    marginTop: 14,
  },
  panel: {
    marginTop: 16,
    maxHeight: 320,
    backgroundColor: colors.paperTop,
    borderWidth: 3,
    borderColor: colors.ink,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    shadowColor: colors.cardShadow,
    shadowOffset: { width: 6, height: 7 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
    overflow: "hidden",
  },
  panelHeader: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: "rgba(20,33,31,.12)",
  },
  panelHeaderText: {
    fontFamily: "InstrumentSerif_400Regular_Italic",
    fontSize: 17,
    color: colors.ink55,
  },
  list: {
    flexGrow: 0,
    maxHeight: 280,
  },
  suggestionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderBottomWidth: 2,
    borderBottomColor: "rgba(20,33,31,.12)",
  },
  suggestionRowLast: {
    borderBottomWidth: 0,
  },
  suggestionIcon: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  suggestionText: {
    flex: 1,
    minWidth: 0,
  },
  suggestionTitle: {
    fontFamily: "Karla_600SemiBold",
    fontSize: 17,
    color: colors.ink,
  },
  suggestionSubtitle: {
    fontFamily: "Karla_400Regular",
    fontSize: 14,
    color: colors.ink45,
    marginTop: 2,
  },
  emptyRow: {
    paddingHorizontal: 18,
    paddingVertical: 20,
    alignItems: "center",
  },
  emptyText: {
    fontFamily: "Karla_400Regular",
    fontSize: 17,
    color: colors.ink45,
    textAlign: "center",
  },
  retryText: {
    fontFamily: "Karla_600SemiBold",
    fontSize: 17,
    color: colors.deepTeal,
  },
});
